FROM nginx:1.23.1-alpine

RUN sed -i -e 's/http:/https:/' /etc/apk/repositories
RUN apk update
RUN apk add bash

RUN mkdir -p /www/static

EXPOSE 1935
EXPOSE 80

CMD envsubst "$(env | sed -e 's/=.*//' -e 's/^/\$/g')" < \
  /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && \
  nginx
